Update app.src
YunoHost-Apps/lufi_ynh pull request #44
Opened 2020-07-25 14:15 UTC by vincentux

Update 0.05.2

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/lufi_ynh%20PR-NUM-%20(USERNAME)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/lufi_ynh%20PR-NUM-%20(USERNAME)/)

2020-09-03 16:12 UTC, alexAubin commented
Sounds like a legit change to me ?

2020-09-16 13:02 UTC, ericgaspar requested changes
As we increment the version number...

2020-09-16 13:02 UTC, ericgaspar commented on manifest.json
> +	"version": "0.05.2~ynh3",
```suggestion
	"version": "0.05.2~ynh1",
```

2020-11-09 22:34 UTC, ericgaspar commented
Outdated with #47

2020-11-09 22:34 UTC, closed without merging