New path for media
YunoHost-Apps/lufi_ynh pull request #59
Opened 2021-04-22 20:27 UTC by ericgaspar

- Set media path to `/home/yunohost.app/lufi` cf #51

2021-04-22 20:28 UTC, ericgaspar commented
!testme

2021-05-08 21:45 UTC, ericgaspar commented
!testme

2021-05-09 08:25 UTC, ericgaspar commented
!testme

2021-05-09 20:04 UTC, ericgaspar commented
!testme

2021-08-16 09:41 UTC, ericgaspar commented
!testme

2021-08-16 11:45 UTC, ericgaspar commented
!testme

2021-09-11 10:30 UTC, ericgaspar commented
!testme

2021-09-12 10:46 UTC, yalh76 requested changes
If it brokes previously uploaded files, it's better not to change the media path
And it would be better not to do different things in the same PR: changing the media path and upgrading the version

2021-09-12 10:46 UTC, yalh76 commented on manifest.json
> +            },
If it brokes previously uploaded files, it's better not to change the media path

2021-09-12 11:01 UTC, closed without merging